"""modified productImage model

Revision ID: 10fc60a2185e
Revises: 374bef2b5883
Create Date: 2026-08-07 02:11:09.348374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fc60a2185e'
down_revision: Union[str, Sequence[str], None] = '374bef2b5883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('public_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'public_id')
    # ### end Alembic commands ###
